name: Feature request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving the plugin.
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmations
      description: By submitting this issue, you confirm
      options:
        - label: There isn't any other PR or issue regarding this.
          required: true
        - label: This feature does not exist in the latest version.
          required: true
  - type: dropdown
    id: type
    attributes:
      label: What is your request about?
      multiple: false
      options:
        - New gun
        - New mechanic
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature
    validations:
      required: true
